import { useMemo } from 'react'
import styled from 'styled-components'

import { DEUS_TOKEN, Tokens, SYMM_TOKEN } from 'constants/tokens'
import MigrationCard from './MigrationCard'
import { useWeb3React } from '@web3-react/core'
import { useTokenBalances } from 'lib/hooks/useCurrencyBalance'
import { useBalancedRatio, useGetUserMigrations } from 'hooks/useMigratePage'
import CongratsCard from './CongratsCard'
import { isMobile } from 'react-device-detect'
import { MigrationOptions, MigrationVersion } from 'constants/migrationOptions'
import { TokenMap } from '@uniswap/sdk-core'

const Wrapper = styled.div`
  display: flex;
  align-items: stretch;
  ${({ theme }) => theme.mediaWidth.upToSmall`
    flex-flow: column wrap;
    padding: 10px;
  `};
`

export default function CardBox() {
  const { account, chainId } = useWeb3React()

  const firstMigrationCardTokens = MigrationOptions.map((option) => {
    if (chainId && option.supportedChains.includes(chainId) && option.version === MigrationVersion.DUAL) {
      return option.token
    }
  }).filter((token) => {
    return !!token
  })

  const migrationCardTokens = MigrationOptions.map((option) => {
    if (chainId && option.supportedChains.includes(chainId)) {
      return option.token
    }
  }).filter((token) => {
    return !!token
  })

  const chainSourceTokens = migrationCardTokens.map((token) => {
    if (chainId && token && token[chainId]) {
      return token[chainId]
    }
  })
  const sourceBalances = useTokenBalances(account?.toString(), chainSourceTokens)

  const inputAmounts = useMemo(() => {
    return chainSourceTokens.map((token) => {
      if (token) return sourceBalances[token?.address]?.quotient.toString()
    })
  }, [sourceBalances, chainSourceTokens])

  const balancedRatio = useBalancedRatio()
  const { userTotalMigration_toDeus, userTotalMigration_toSymm } = useGetUserMigrations(Number(balancedRatio), account)

  const [isFullyEmpty, isFullyMigrated] = useMemo(() => {
    for (let index = 0; index < inputAmounts.length; index++) {
      if (inputAmounts[index] !== '0') return [false, false]
    }
    return [true, userTotalMigration_toDeus.toString() !== '0' || userTotalMigration_toSymm.toString() !== '0']
  }, [inputAmounts, userTotalMigration_toDeus, userTotalMigration_toSymm])

  return (
    <Wrapper>
      {(!isFullyMigrated || !isMobile) && (
        <MigrationCard
          disabled={isFullyMigrated}
          destinationTokens={[DEUS_TOKEN]}
          sourceTokens={firstMigrationCardTokens as TokenMap[]}
          firstDescription="DEUS will focus on the stablecoin concept while leveraging amassed veNFTs for yield generation through liquidity AMOs."
          secondDescription=" DEUS stakers will receive 100% of all fees generated through stablecoin minting, AMOs and future stablecoin products."
        />
      )}
      {!isFullyMigrated ? (
        <MigrationCard
          disabled={isFullyMigrated}
          destinationTokens={[DEUS_TOKEN, SYMM_TOKEN]}
          sourceTokens={migrationCardTokens as TokenMap[]}
          firstDescription="BALANCED migration will ensure the user's investment ratio remains the same as before the split, with exposure to perps and stablecoin maintained precisely."
          secondDescription="Migrate easily and confidently to not miss out on any development by choosing the balanced migration approach."
        />
      ) : (
        <CongratsCard
          destinationTokens={[DEUS_TOKEN, SYMM_TOKEN]}
          sourceTokens={[Tokens['DEUS'], Tokens['XDEUS'], Tokens['LEGACY_DEI'], Tokens['bDEI_TOKEN']]}
          deus={userTotalMigration_toDeus.toFixed(2).toString()}
          symm={userTotalMigration_toSymm.toFixed(2).toString()}
        />
      )}
      {(!isFullyMigrated || !isMobile) && (
        <MigrationCard
          disabled={isFullyMigrated}
          destinationTokens={[SYMM_TOKEN]}
          sourceTokens={migrationCardTokens as TokenMap[]}
          firstDescription='The SYMMIO project will continue advancing the P2P bilateral (symmetrical) derivatives concept initially called "DEUS v3."'
          secondDescription="Upon migrating to SYMM, migrators will be issued $SYMM tokens, and $SYMM stakers will enjoy 100% of all fees generated by all third-party frontends."
        />
      )}
    </Wrapper>
  )
}
